### ISSUE TITLE
拍照闪念窗口与以下css冲突

### ISSUE THREAD

**Issue by 5kyfkr** [IAliceBobI/sy-tomato-plugin#36]
如题，添加了以下删除这两个图标的css代码会导致无法移动窗口，如果修不好就算了，就在正中间也没事

```css
.layout-tab-bar--readonly {display: none}
``` 
就是下图这两个图标
![image](https://github.com/IAliceBobI/sy-tomato-plugin/assets/63196026/9bcd103a-b732-4a4a-9218-8b8d8996090a)

**Comment by IAliceBobI** [comment]
移动就靠 .layout-tab-bar 了。 你还把他禁用。

**Comment by 5kyfkr** [comment]
> 移动就靠 .layout-tab-bar 了。 你还把他禁用。

那就算了，有没有其他办法关了这两个图标

**Comment by IAliceBobI** [comment]
@5kyfkr 我开发的时候就遇到了。我也关闭过，发现无法移动。其他的按钮我也关闭了。

https://github.com/IAliceBobI/sy-plugins/blob/main/sy-tomato-plugin/src/NoteBox.ts#L28-L39

**Comment by 5kyfkr** [comment]
> @5kyfkr 我开发的时候就遇到了。我也关闭过，发现无法移动。其他的按钮我也关闭了。

好滴，那不管了，固定就固定了

**Comment by IAliceBobI** [comment]
```
 document.querySelectorAll('span[data-type="new"][aria-label="新建文档"]').forEach((e: HTMLElement) => {
        if (e.style) e.style.display = "none";
    });
    document.querySelectorAll('span[data-type="more"][aria-label="页签切换"]').forEach((e: HTMLElement) => {
        if (e.style) e.style.display = "none";
    });
```


我的意思是说你看这代码，可以用。

**Comment by IAliceBobI** [comment]
这就是你那两个想要隐藏的按钮。他们都在layout-tab-bar上。 你之前直接干掉这个layout-tab-bar，是简单了。但不能拖动。需要把layout-tab-bar上的两个我个你的精确干掉。

**Comment by 5kyfkr** [comment]
> 这就是你那两个想要隐藏的按钮。他们都在layout-tab-bar上。 你之前直接干掉这个layout-tab-bar，是简单了。但不能拖动。需要把layout-tab-bar上的两个精确干掉。
> 
> @5kyfkr

试了确实可以，感谢大佬提供思路
```css
span[data-type="new"][aria-label="新建文档"] { display: none; }
span[data-type="more"][aria-label="页签切换"] { display: none; }
```
